name: Release
on:
    push:
        tags:
            - '*.*.*'
permissions:
    contents: read
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: Restore
              run: dotnet restore
            - name: Build
              run: dotnet build -c Release --no-restore
            - name: Test
              run: dotnet test --no-build -c Release --verbosity normal
            - name: Create packages
              run: dotnet pack --no-build -c Release --no-restore -o artifacts
            - name: Push to myget
              run: dotnet nuget push "**/*.nupkg" --source https://www.myget.org/F/hierarchybuilder/api/v3/index.json --api-key ${NUGET_API_KEY}
              env:
                  NUGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
            -   name: Push to myget
                run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
                env:
                    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
            - name: Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: artifacts
                  path: artifacts/**/*
